APP:
  ACCESS_TOKEN: "irc_access_token" ## Get from https://twitchtokengenerator.com
  CLIENT_SECRET: "client_secret" ## App Client Secret
  CLIENT_ID: "client_id" ## App Client ID
  SECRET_STRING: "any_secret_string"
  CALLBACK_URL: "https://twitchbot.example.co.uk/callback"
  PORT: 4000
  BOT_GITHUB_LINK: "https://github.com/adambirds/pythonrobot-twitch-bot"
  BOT_COMMANDS_LINK: "https://github.com/adambirds/pythonrobot-twitch-bot#commands"
  DATABASE:
    DBUSER: ""
    DBNAME: ""
    DBHOST: "127.0.0.1"
    DBPASS: ""
    DBPORT: 5432
  ACCOUNTS: [
      {
        name: "channel1name", # Channel Name
        id: 111111111, # Channel Broadcast ID
      },
      {
        name: "channel2name", # Channel Name
        id: 222222222, # Channel Broadcast ID
      },
    ]
codingandgamingwithadam:
  SOCIALS:
    GITHUB: "https://github.com/adambirds"
    DISCORD: "https://discord.gg/f5veJaa4ZX"
    YOUTUBE: ""
    INSTAGRAM: ""
    TWITTER: ""
    TIKTOK: ""
    FACEBOOK: ""
    WEBSITE: ""
    REDDIT: ""
pythonphil:
  SOCIALS:
    GITHUB: "https://github.com/GunnerShents"
    DISCORD: "https://discord.gg/WTaUVMk5cE"
    YOUTUBE: ""
    INSTAGRAM: ""
    TWITTER: ""
    TIKTOK: ""
    FACEBOOK: ""
    WEBSITE: ""
    REDDIT: ""
