#!/usr/bin/env bash

# This hook runs gitlint on your commit message.

# Do not invoke gitlint if commit message is empty
if grep -q '^[^#]' "$1"; then
	lint_cmd="tools/lint --only=gitlint"
	if
		! eval "$lint_cmd" <"$1"
	then
		echo "WARNING: Your commit message does not match pythonrobot-twitch-bot's style guide."
	fi
fi

exit 0
